In [2]:
pip install tensorflow-gpu==1.13.1

ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.13.1 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.12.0)
ERROR: No matching distribution found for tensorflow-gpu==1.13.1


In [12]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.17.0'

In [5]:
tensor = tf.constant([[23,4],[32,51]])

In [6]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [9]:
variable = tf.Variable([[30,20],[10,45]])

In [10]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

In [15]:
tensor2 = tf.constant([[23,4],[32,51]])

In [16]:
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [18]:
tensor2.shape

TensorShape([2, 2])

In [19]:
tensor2.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [20]:
numpy_tensor = np.array([[15,23],[40,35]])

In [22]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [23]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[15, 23],
       [40, 35]])>

In [24]:
tensor2_variable = tf.Variable([[3.,4.,10.],[5.,3.,1.]])
tensor2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 3.,  4., 10.],
       [ 5.,  3.,  1.]], dtype=float32)>

In [26]:
tensor2_variable.numpy()

array([[ 3.,  4., 10.],
       [ 5.,  3.,  1.]], dtype=float32)

In [28]:
tensor2_variable[0,1].assign(7)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 3.,  7., 10.],
       [ 5.,  3.,  1.]], dtype=float32)>

In [29]:
tensor2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 3.,  7., 10.],
       [ 5.,  3.,  1.]], dtype=float32)>

In [32]:
tensor = tf.constant([[1,2],[3,4]])

In [33]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [34]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [36]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [37]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [38]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [39]:
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [40]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [41]:
np.dot(tensor,tensor2)

array([[ 87, 106],
       [197, 216]], dtype=int32)

In [42]:
tfstring = tf.constant('TensorString')
tfstring

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorString'>

In [44]:
tf.strings.length(tfstring)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [45]:
tf.strings.unicode_decode(tfstring,"UTF8")

<tf.Tensor: shape=(12,), dtype=int32, numpy=
array([ 84, 101, 110, 115, 111, 114,  83, 116, 114, 105, 110, 103],
      dtype=int32)>

In [46]:
tf_string_array = tf.constant(['Tf','deep','test'])

In [47]:
for i in tf_string_array:
    print(i)

tf.Tensor(b'Tf', shape=(), dtype=string)
tf.Tensor(b'deep', shape=(), dtype=string)
tf.Tensor(b'test', shape=(), dtype=string)
